### ISSUE TITLE
You might get sued...

### ISSUE THREAD

**Issue by jasonwynn10** [remotevase/remotevase.github.io#1]
If you leave no mention of html5 you can get sued by them. They are the ones who really made the design, so whether you changed something or not, according to the license they used on this design they can sue you for claiming you made it

**Comment by remotevase** [comment]
I never claimed that I made it... I also never claimed that they made it... Oops... I'll add that in later...

**Comment by jasonwynn10** [comment]
put it in the footer

**Comment by remotevase** [comment]
...
